name: dusty-gan
dependencies:
  - cudatoolkit=11.0
  - matplotlib
  - python=3.7
  - pytorch::pytorch=1.7.1
  - pytorch::torchvision
  - tqdm
  - pip:
    - black
    - hydra-core
    - hydra_colorlog
    - joblib
    - mypy
    - omegaconf
    - opencv-python
    - scikit-learn
    - tensorflow
    - numba
    - psutil