cuda: true
num_workers: 8
pin_memory: true
resume: null
enable_amp: true

dist_backend: nccl
seed: null
multiprocessing_distributed: true
publish_wandb: false

defaults:
  - dataset: kitti_odometry
  - model: dusty1_dcgan_eqlr
  - solver: nsgan

hydra:
  run:
    dir: outputs/logs/dataset=${hydra.runtime.choices.dataset}/model=${hydra.runtime.choices.model}/solver=${hydra.runtime.choices.solver}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/logs/dataset=${hydra.runtime.choices.dataset}/model=${hydra.runtime.choices.model}/solver=${hydra.runtime.choices.solver}/${now:%Y-%m-%d}/${now:%H-%M-%S}
