cuda: true
num_workers: 4
pin_memory: true
resume: null

dist_backend: nccl
seed: null
multiprocessing_distributed: true
publish_wandb: true

defaults:
  - dataset: kitti_odometry
  - model: dusty1_dcgan_eqlr
  - solver: nsgan

  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: outputs/${hydra.job.override_dirname}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/${hydra.job.override_dirname}/${now:%Y-%m-%d}/${now:%H-%M-%S}
